name: Java CI with Maven and JaCoCo (trying again 6)

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Java JDK on ${{ matrix.os }}
        uses: actions/setup-java@v3.10.0
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Install Xvfb
        run: sudo apt-get install -y xvfb
      - name: Run Xvfb
        run: Xvfb :99 &
        env:
          DISPLAY: :99
      - name: Build with Maven on ${{ matrix.os }}
        run: mvn package
      - name: Run unit tests
        run: DISPLAY=:99 mvn test
      - name: Generate JaCoCo report
        run: mvn test jacoco:report
      - name: Generate Javadoc
        run: mvn javadoc:javadoc